### ISSUE TITLE
Architecture translate recommendation

### ISSUE THREAD

**Issue by yanshengjie** [mspnp/architecture-center.zh-cn#24]
Currently, the 'Architecture' has been translated to ”体系结构“ in all pages of the document. That is improperly. I prefer to translate to ”架构“.

**Comment by gosali** [comment]
Hello, @yanshengjie ,
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.
Does this change belong to an specific page or it is a general feedback?

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @yanshengjie

Thank you for your linguistic feedback. 
 
Unfortunately, after reviewing your feedback our linguistic team considered it to be not fully aligned with our criteria for acceptance:

>The suggested translation "架构" indeed sounds more succinct. However, "体系结构" is not an incorrect translation. In addition, "架构" is also the TS approved term for "schema". So using the existing translation "体系结构" helps keep the distinction between "architecture" and "schema". So for the moment, I wouldn't suggest a global change.

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards,
Microsoft DOCS International Team
