### ISSUE TITLE
我

### ISSUE THREAD

**Issue by dwj83624** [mspnp/architecture-center.zh-cn#42]
[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 0a4ecd26-cb7b-4cb2-ae3a-3748ada92771
* Version Independent ID: 97f96179-a22b-8401-a2f4-264a86b5d2f5
* Content: [云设计模式](https://docs.microsoft.com/zh-cn/azure/architecture/patterns/index)
* Content Source: [docs/patterns/index.md](https://github.com/mspnp/architecture-center.zh-cn/blob/live/docs/patterns/index.md)
* Service: **guidance**
* GitHub Login: @olprod
* Microsoft Alias: **pnp**

**Comment by CeciAc** [comment]
你好，@dwj83624

你的注释违反了我们行为准则，见 https://opensource.microsoft.com/codeofconduct/。  

因此，我们需要锁定并关闭此问题。 


深深的祝福， 
Microsoft DOCS International Team
