### ISSUE TITLE
Pictures are inaccessible in this article

### ISSUE THREAD

**Issue by adoyle-h** [mspnp/architecture-center.zh-cn#69]
When I browsing the page https://docs.microsoft.com/zh-cn/azure/architecture/patterns/sharding, I get empty pictures in below links:
https://docs.microsoft.com/zh-cn/azure/architecture/patterns/_images/sharding-tenant.png
https://docs.microsoft.com/zh-cn/azure/architecture/patterns/_images/sharding-sequential-sets.png
https://docs.microsoft.com/zh-cn/azure/architecture/patterns/_images/sharding-data-hash.png

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 050bb1fd-56ca-63bc-b105-17a56e3b0362
* Version Independent ID: ce84d0a7-3596-e259-dfc3-a9789efd9948
* Content: [分片](https://docs.microsoft.com/zh-cn/azure/architecture/patterns/sharding#feedback)
* Content Source: [docs/patterns/sharding.md](https://github.com/mspnp/architecture-center.zh-cn/blob/live/docs/patterns/sharding.md)
* Service: **guidance**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by adoyle-h** [comment]
By the way, I cannot submit an issue written in Chinese.
It show that
![image](https://user-images.githubusercontent.com/1998490/47763160-81a7e980-dcfa-11e8-83b9-c2d2851eff38.png)

**Comment by CeciAc** [comment]
Hello, @adoyle-h,
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@Sara-Nicolini can you please check the issue the contributor is reporting about submitting the issue in Chinese? I made a quick test, it looks like you can write Chinese in the body of the issue but not in the title.

**Comment by CeciAc** [comment]
Hello, @adoyle-h,

Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages  https://docs.microsoft.com/zh-cn/azure/architecture/patterns/sharding

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
